import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import textwrap
from scipy.signal import find_peaks, medfilt
from scipy.special import gamma
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.widgets import Button


def build_piecewise(time, t_discs, params, prefix):

    # Check for prefix in params
    keys = sorted(
        [k for k in params if k.startswith(prefix)], key=lambda k: int(k[len(prefix) :])
    )

    # Extract parameter values
    values = np.array(
        [params[k].value if hasattr(params[k], "value") else params[k] for k in keys]
    )

    # Assign parameter values to corresponding index based on time discontinuities
    idx = np.digitize(time, t_discs[:-1], right=True) - 1
    idx = np.clip(idx, 0, len(values) - 1)

    # Return piecewise constant array
    return values[idx]


# finds useful summary parameters from CV data
class CV:
    def __init__(self, userinput_dict):

        df = CV_reader(userinput_dict)
        self.filename = userinput_dict["filename"]
        self.dataframe = df

        # assign variables
        self.i_min_pot = df["E"].idxmin()
        self.i_max_pot = df["E"].idxmax()
        self.max_pot = df["E"][self.i_max_pot]
        self.min_pot = df["E"][self.i_min_pot]
        self.V_per_index = abs(
            round((self.max_pot - self.min_pot) / (self.i_max_pot - self.i_min_pot), 3)
        )

        # finds indices of switching potentials
        potential_gradient = np.gradient(df["E"])
        self.i_switch_pot = np.where(abs(potential_gradient) < self.V_per_index * 0.5)[
            0
        ]  # decimal used as margin for noise in gradient
        self.t_switch_pot = df["Time"][self.i_switch_pot]

        peak_width = int(
            0.03 / self.V_per_index
        )  # 30 mV peak width used as parameter in find_peaks

        # iterate through scans, finding peaks and saving indices in list of lists
        self.peaks = []
        for scan in range(len(self.i_switch_pot) + 1):
            pass

        self.ox_peaks, ox_peak_props = find_peaks(
            np.array(df["I"]), width=peak_width, height=0
        )

        self.red_peaks, red_peak_props = find_peaks(
            -np.array(df["I"]), width=peak_width, height=0
        )

        # find larger peak for scaling
        try:
            if df["I"][self.ox_peaks[0]] > abs(df["I"][self.red_peaks[0]]):
                scaling_current = df["I"][self.ox_peaks[0]]
            else:
                scaling_current = abs(df["I"][self.red_peaks[0]])

        except:
            scaling_current = abs(df["I"]).max()

        # current scaling
        if 1 > scaling_current >= 1e-3:
            self.scaler = 10**3
            report_scale_prefix = scale_prefix = "m"

        elif 1e-3 > scaling_current >= 1e-6:
            self.scaler = 10**6
            scale_prefix = "\u03bc"
            report_scale_prefix = "u"

        elif 1e-6 > scaling_current >= 1e-9:
            self.scaler = 10**9
            report_scale_prefix = scale_prefix = "n"

        elif 1e-9 > scaling_current:
            self.scaler = 10**12
            report_scale_prefix = scale_prefix = "p"

        df["I"] *= self.scaler
        self.scale_prefix = scale_prefix
        self.report_scale_prefix = report_scale_prefix

    def __str__(self):
        return f"CV class created from following file:\n\t{self.filename}"


"""
reads data from CV data files generated by various potentiostat programs and returns 
pandas dataframe with potential, current, and time columns
"""


def CV_reader(userinput_dict):
    if userinput_dict["data_format"] == "CH Instruments text file":
        with open(userinput_dict["filename"], "r", encoding="utf-8") as file:
            lines = file.readlines()
            counter = 0
            for line in lines:
                if line.count("Scan Rate (V/s) =") == 1:
                    rate_char = line.find("=") + 2
                    scan_rate = float(line[rate_char:])

                if line.count("Sample Interval (V)") == 1:
                    interval_char = line.find("=") + 2
                    V_per_index = float(line[interval_char:])

                # find header line and detect delimiter
                if line.count("Potential/V") == 1:
                    header_lines = counter
                    separator_char = line.find("V") + 1
                    separator = repr(line[separator_char]).strip("'")
                counter += 1

        df = pd.read_csv(
            userinput_dict["filename"], skiprows=header_lines, sep=separator
        )
        df.columns = ["E", "I"]
        time = df.index * V_per_index / scan_rate
        df["Time"] = time
        return df

    if userinput_dict["data_format"] == "DigiElch txt":
        scan_rate = userinput_dict["scan_rate"]
        df = pd.read_csv(
            userinput_dict["filename"],
            header=None,
            skiprows=2,
            encoding="utf-8",
            sep="\t",
        )
        df.columns = ["E", "I"]
        df["I"] *= -1  # correction for non IUPAC format
        V_per_index = 0.005
        df["Time"] = df.index * V_per_index / scan_rate
        scaler = 1e6
        return df

    if userinput_dict["data_format"] == "Nova ASCII export":
        df = pd.read_csv(userinput_dict["filename"])
        df = df.drop(
            columns=[
                "WE(1).Potential (V)",
                "Scan",
                "Index",
                "Q+",
                "Q-",
                "Current range",
            ]
        )
        df = df.rename(
            columns={
                "Potential applied (V)": "E",
                "Time (s)": "Time",
                "WE(1).Current (A)": "I",
            }
        )
        # correction for t_0 != 0
        df["Time"] = df["Time"] - df["Time"][0]
        return df

    if userinput_dict["data_format"] == "PSTrace CSV export":
        # read in data to dataframe
        df = pd.read_csv(userinput_dict["filename"], header=4, encoding="utf-16_le")
        df.columns = ["E", "I"]
        # remove byte order mark and convert data to float
        df = df[df["E"] != "\ufeff"]
        df = df.astype(float)

        # read current header to find current magnitude and convert to A
        with open(userinput_dict["filename"], "r", encoding="utf-16") as file:
            lines = file.readlines()
            scale_char = lines[5].find(",") + 1
            scaler = lines[5][scale_char]
        if scaler == "m":
            df["I"] *= 1e-3
        if scaler == "µ":
            df["I"] *= 1e-6
        if scaler == "n":
            df["I"] *= 1e-9
        if scaler == "p":
            df["I"] *= 1e-12

        # use scanrate from userinput_dict to generate time column
        V_per_index = abs(
            round(
                (df["E"].max() - df["E"].min()) / (df["E"].idxmax() - df["E"].idxmin()),
                3,
            )
        )
        time = df.index * V_per_index / userinput_dict["scan_rate"]
        df["Time"] = time

        return df

    if userinput_dict["data_format"] == "Template CSV file":
        with open(userinput_dict["filename"], "r", encoding="utf-8") as file:
            lines = file.readlines()
            rate_char = lines[0].find(",")
            scan_rate = float(lines[0][rate_char + 1 :])

        # create df using filename and remove NaN rows and columns in case template file was modified
        df = pd.read_csv(
            userinput_dict["filename"], skiprows=1, encoding="utf-8", sep=","
        )
        df = df.dropna(axis=0, how="all")
        df = df.dropna(axis=1, how="all")
        df.columns = ["E", "I"]

        # calculate V_per_index and use scan_rate to calculate time column
        V_per_index = abs(
            round(
                (df["E"].max() - df["E"].min()) / (df["E"].idxmax() - df["E"].idxmin()),
                3,
            )
        )
        time = df.index * V_per_index / scan_rate
        df["Time"] = time
        return df


# numerical differintegration function (general form equation 8.2.8) using RL algorithm from Oldham and Spanier (2006)
def diff_int(x, y, q):
    N_array = np.arange(0, len(x))
    j_array = np.arange(0, len(x))
    largest_N = len(x) - 1

    # create quotient array
    quotient_array = np.zeros(len(x))
    quotient_array[1:] = N_array[1:] ** q / x[1:] ** q

    # weight function array
    wf_array = np.zeros(len(x))
    wf_array[0] = 1 / gamma(2 - q)
    wf_array[1:] = (
        (j_array[1:] + 1) ** (1 - q)
        - 2 * j_array[1:] ** (1 - q)
        + (j_array[1:] - 1) ** (1 - q)
    ) / gamma(2 - q)

    # create fj array with y data
    fj_array = np.flip(y)

    # create array for summation values
    summation_array = np.zeros(len(x))

    # iterate through N values, populating array with summation
    N = 1
    while N <= largest_N:
        summation_array[N] = np.sum(wf_array[: N + 1] * fj_array[largest_N - N :])
        N += 1

    return quotient_array * summation_array


def pdf_summary(userinput_dict, name, ip_list, Ep_list, cv, result, baseline_df):
    with PdfPages(f"{userinput_dict['output_dir']}/{name}.pdf") as pdf:
        # unpack inputs
        potential = np.array(cv.dataframe["E"])
        current = np.array(cv.dataframe["I"])
        time = np.array(cv.dataframe["Time"])
        transform = diff_int(time, current, 1 / 2)
        components = result.eval_components()

        # setup colour palette (Okabe-Ito)
        okabe_ito = [
            "#E69F00",  # orange
            "#56B4E9",  # sky blue
            "#009E73",  # bluish green
            "#F0E442",  # yellow
            "#0072B2",  # blue
            "#D55E00",  # vermilion
            "#CC79A7",  # reddish purple
            "#000000",  # black
        ]

        # A4 size in inches (portrait)
        A4_portrait = (8.27, 11.69)
        fig, axs = plt.subplots(
            2, 1, figsize=A4_portrait, gridspec_kw={"height_ratios": [1, 1]}
        )

        plt.subplots_adjust(left=0.15, right=0.85, hspace=0.4)

        # PAGE 1
        # Page 1: Top half (CV plot with baselines)
        ax_plot = axs[0]
        ax_plot.plot(potential, current)
        current_margin = (current.max() - current.min()) * 0.15
        ylim = (current.min() - current_margin, current.max() + current_margin)
        ax_plot.set(ylim=ylim, xlabel="Potential (V)", ylabel=f"i ({cv.scale_prefix}A)")

        # generate baselines and ip labels
        counter = 0
        for col in baseline_df.columns:
            if "Peak" not in col:
                continue

            colour = okabe_ito[counter % len(okabe_ito)]
            base = np.array(baseline_df[col].dropna())
            idx_ip = len(base)
            ax_plot.plot(potential[:idx_ip], base, color=colour, ls="dashed")
            ax_plot.vlines(
                potential[idx_ip], base[-1], current[idx_ip], color=colour, ls="dashed"
            )

            ip_label = f"{counter+1}"
            ip_label_offset = (
                abs(ip_list[counter])
                / ip_list[counter]
                * (current.max() - current.min())
                * 0.08
            )
            ax_plot.text(
                potential[idx_ip],
                current[idx_ip] + ip_label_offset,
                ip_label,
                ha="center",
                va="center",
            )
            counter += 1

        # Page 1: Bottom half (i_p summary table)
        if len(ip_list) > 0:
            table_data = []
            for i, val in enumerate(ip_list, start=1):
                name = f"{i}"
                table_data.append([name, round(val, 2), round(Ep_list[i - 1], 3)])
            ax_table = axs[1]
            ax_table.axis("off")

            ax_table.text(
                0.5,
                0.95,
                "i$_p$ summary",
                ha="center",
                va="top",
                fontsize=14,
                fontweight="bold",
            )

            # Table
            table = ax_table.table(
                cellText=table_data,
                colLabels=["Peak no.", f"i$_p$ ({cv.scale_prefix}A)", r"E$_p$ (V)"],
                cellLoc="center",
                loc="center",
            )

            # Bold column headings
            for (row, col), cell in table.get_celld().items():
                if row == 0:  # row 0 = header row
                    cell.set_text_props(fontweight="bold")

            table.auto_set_font_size(False)
            table.set_fontsize(9)
            table.scale(0.8, 1.4)

            pdf.savefig(fig, dpi=300)
            plt.close(fig)

        # PAGE 2
        # Page2: Top half (semiderivative fit components)
        fig, axs = plt.subplots(
            2, 1, figsize=A4_portrait, gridspec_kw={"height_ratios": [1, 1]}
        )
        plt.subplots_adjust(left=0.15, right=0.85, hspace=0.4)

        axs[0].set(
            title="Semi-derivative and fitted functions",
            xlabel="Time (s)",
            ylabel=f"e ({cv.scale_prefix}A s$^{{-1/2}}$)",
        )
        axs[0].plot(time, transform)
        for comp in components:
            comp_label = comp.removesuffix("_")
            axs[0].plot(time, components[comp], label=comp_label, ls="dashed")
        axs[0].legend()

        # Page 2: Bottom half (deconvolved fits with current)
        axs[1].set(
            title="Current and semi-integrals of fitted functions",
            xlabel="Time (s)",
            ylabel=f"i ({cv.scale_prefix}A)",
        )
        axs[1].plot(time, current)
        for comp in components:
            comp_label = comp.removeprefix("SD_")
            comp_label = comp_label.removesuffix("_")
            axs[1].plot(
                time,
                diff_int(time, components[comp], -1 / 2),
                label=comp_label,
                ls="dashed",
            )
        axs[1].legend()

        pdf.savefig(fig, dpi=300)
        plt.close(fig)

        # PAGE 3
        # lm fit summary

        report = result.fit_report()
        wrapped_lines = []
        for line in report.split("\n"):
            wrapped = textwrap.wrap(line, width=95)
            if not wrapped:  # preserve blank lines
                wrapped_lines.append("")
            else:
                wrapped_lines.extend(wrapped)

        # Split into pages
        lines_per_page = 55
        chunks = [
            wrapped_lines[i : i + lines_per_page]
            for i in range(0, len(wrapped_lines), lines_per_page)
        ]

        for page_num, chunk in enumerate(chunks, start=1):
            fig, ax = plt.subplots(figsize=A4_portrait)
            ax.axis("off")

            ax.text(
                0.5,
                0.97,
                f"lmfit Fit Report (Page {page_num})",
                ha="center",
                va="top",
                fontsize=14,
                fontweight="bold",
            )

            text_block = "\n".join(chunk)
            ax.text(
                0, 0.93, text_block, ha="left", va="top", fontsize=9, family="monospace"
            )

            pdf.savefig(fig, dpi=300)
            plt.close(fig)


def peak_finder_auto(y, bkg, width):

    # smoothing for transient spikes
    transform_smoothed = medfilt(y, kernel_size=7)

    prom = abs(y).max() * 0.02
    pos_peaks = find_peaks(
        transform_smoothed, prominence=prom, height=bkg, width=width
    )[0]

    neg_peaks = find_peaks(
        -transform_smoothed, prominence=prom, height=bkg, width=width
    )[0]

    peak_array = np.sort(np.concatenate((pos_peaks, neg_peaks)))
    return peak_array


manual_picking_finished = False


def peak_finder_manual(cv, y):
    global manual_picking_finished
    manual_picking_finished = False

    x = np.array(cv.dataframe["Time"])

    fig, ax = plt.subplots()
    fig.canvas.manager.set_window_title("Manual Peak Selection")
    ax.plot(x, y, lw=1.2)
    ax.set_title(
        "Left-click: add peak   |   Right-click: delete peak\n"
        "Close this window when finished"
    )
    ax.set_xlabel("Time (s)")
    ax.set_ylabel(rf"e ({cv.scale_prefix}A s$^{{-1/2}}$)")

    peaks = []
    markers = []

    def onclick(event):
        if event.inaxes != ax or event.xdata is None:
            return

        # prevents peak assignment when using zoom or panning tools
        toolbar = fig.canvas.manager.toolbar
        if toolbar.mode != "":
            return

        # nearest data index to the click
        click_idx = int(np.argmin(np.abs(x - event.xdata)))

        # add marker with left click
        if event.button == 1:
            peaks.append(click_idx)
            (m,) = ax.plot(x[click_idx], y[click_idx], "ro", markersize=6)
            markers.append(m)
            fig.canvas.draw_idle()
            return

        # remove nearest marker with right click
        if event.button == 3 and peaks:
            distances = [abs(pi - click_idx) for pi in peaks]
            nearest_idx = int(np.argmin(distances))
            del peaks[nearest_idx]
            marker = markers.pop(nearest_idx)
            marker.remove()
            fig.canvas.draw_idle()

    cid = fig.canvas.mpl_connect("button_press_event", onclick)

    def on_close(event):
        global manual_picking_finished
        fig.canvas.mpl_disconnect(cid)
        manual_picking_finished = True

    fig.canvas.mpl_connect("close_event", on_close)

    plt.show(block=False)
    return peaks


def xlsx_summary(userinput_dict, name, df, baseline_df, cv, n_components):
    current_df = df.iloc[
        :, : -n_components - 2
    ]  # exlcudes SD fit components, SD transform, and SD total fit
    SD_df = pd.concat(
        [df.iloc[:, :2], df.iloc[:, -n_components - 2 :]], axis=1
    )  # keeps time, potential, SD transform, and SD fit components
    with pd.ExcelWriter(
        f"{userinput_dict['output_dir']}/{name}.xlsx", engine="xlsxwriter"
    ) as writer:
        baseline_df.to_excel(writer, sheet_name="baselines", index=False)
        current_df.to_excel(writer, sheet_name="current", index=False)
        SD_df.to_excel(writer, sheet_name="semi-derivative", index=False)

        workbook = writer.book

        # BASELINE PLOTS
        t_chart = workbook.add_chart({"type": "scatter", "subtype": "straight"})
        E_chart = workbook.add_chart({"type": "scatter", "subtype": "straight"})
        nrows, ncols = baseline_df.shape
        for col in range(2, ncols):
            t_chart.add_series(
                {
                    "name": ["baselines", 0, col],
                    "categories": [
                        "baselines",
                        1,
                        0,
                        nrows,
                        0,
                    ],
                    "values": [
                        "baselines",
                        1,
                        col,
                        nrows,
                        col,
                    ],
                }
            )
            t_chart.set_x_axis(
                {"name": "Time (s)", "label_position": "low", "crossing": "min"}
            )
            t_chart.set_y_axis(
                {"name": f"i ({cv.scale_prefix}A)", "label_position": "low"}
            )

            E_chart.add_series(
                {
                    "name": ["baselines", 0, col],
                    "categories": [
                        "baselines",
                        1,
                        1,
                        nrows,
                        1,
                    ],
                    "values": [
                        "baselines",
                        1,
                        col,
                        nrows,
                        col,
                    ],
                }
            )
            E_chart.set_x_axis(
                {
                    "name": "Potential (V)",
                    "label_position": "low",
                    "crossing": "min",
                }
            )
            E_chart.set_y_axis(
                {"name": f"i ({cv.scale_prefix}A)", "label_position": "low"}
            )
        # Insert chart in the sheet
        writer.sheets["baselines"].insert_chart("D4", t_chart)
        writer.sheets["baselines"].insert_chart("D20", E_chart)

        # CURRENT PLOTS
        t_chart = workbook.add_chart({"type": "scatter", "subtype": "straight"})
        E_chart = workbook.add_chart({"type": "scatter", "subtype": "straight"})
        nrows, ncols = current_df.shape
        for col in range(2, ncols):
            t_chart.add_series(
                {
                    "name": ["current", 0, col],
                    "categories": [
                        "current",
                        1,
                        0,
                        nrows,
                        0,
                    ],
                    "values": [
                        "current",
                        1,
                        col,
                        nrows,
                        col,
                    ],
                }
            )
            t_chart.set_x_axis(
                {"name": "Time (s)", "label_position": "low", "crossing": "min"}
            )
            t_chart.set_y_axis(
                {"name": f"i ({cv.scale_prefix}A)", "label_position": "low"}
            )

            E_chart.add_series(
                {
                    "name": ["current", 0, col],
                    "categories": [
                        "current",
                        1,
                        1,
                        nrows,
                        1,
                    ],
                    "values": [
                        "current",
                        1,
                        col,
                        nrows,
                        col,
                    ],
                }
            )
            E_chart.set_x_axis(
                {
                    "name": "Potential (V)",
                    "label_position": "low",
                    "crossing": "min",
                }
            )
            E_chart.set_y_axis(
                {"name": f"i ({cv.scale_prefix}A)", "label_position": "low"}
            )
        # Insert chart in the sheet
        writer.sheets["current"].insert_chart("D4", t_chart)
        writer.sheets["current"].insert_chart("D20", E_chart)

        # SEMI-DERIVATIVE PLOTS
        t_chart = workbook.add_chart({"type": "scatter", "subtype": "straight"})
        E_chart = workbook.add_chart({"type": "scatter", "subtype": "straight"})
        nrows, ncols = SD_df.shape
        for col in range(2, ncols):
            col_name = SD_df.columns[col]
            t_chart.add_series(
                {
                    "name": ["semi-derivative", 0, col],
                    "categories": [
                        "semi-derivative",
                        1,
                        0,
                        nrows,
                        0,
                    ],
                    "values": [
                        "semi-derivative",
                        1,
                        col,
                        nrows,
                        col,
                    ],
                }
            )
            t_chart.set_x_axis(
                {"name": "Time (s)", "label_position": "low", "crossing": "min"}
            )
            t_chart.set_y_axis(
                {
                    "name": f"e ({cv.scale_prefix}A s^(-1/2))",
                    "label_position": "low",
                }
            )
            E_chart.add_series(
                {
                    "name": ["semi-derivative", 0, col],
                    "categories": [
                        "semi-derivative",
                        1,
                        1,
                        nrows,
                        1,
                    ],
                    "values": [
                        "semi-derivative",
                        1,
                        col,
                        nrows,
                        col,
                    ],
                }
            )

            E_chart.set_x_axis(
                {
                    "name": "Potential (V)",
                    "label_position": "low",
                    "crossing": "min",
                }
            )
            E_chart.set_y_axis(
                {
                    "name": f"e ({cv.scale_prefix}A s^(-1/2))",
                    "label_position": "low",
                }
            )
        # Insert chart in the sheet
        writer.sheets["semi-derivative"].insert_chart("D4", t_chart)
        writer.sheets["semi-derivative"].insert_chart("D20", E_chart)
